apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-1
  namespace: demo
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx-1
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      containers:
      - name: nginx
        image: nginx
        # resources:
        #   requests:
        #     memory: "6Gi"
        ports:
        - containerPort: 80