apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-1
  name: nginx-1
  namespace: demo
spec:
  ports:
  - name: "80"
    port: 80
  selector:
    app: nginx-1
status:
  loadBalancer: {}

